authenticator/urls.py
from django.urls import path

from . import views

app_name = "authenticator"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("register", views.register_view, name="register"),
    path("dashboard", views.dashboard_view, name="dashboard"),
    path("logout", views.logout_view, name="logout"),
]

createbio/urls.py
from django.urls import path

from . import views

app_name = "createbio"
urlpatterns = [
    path("", views.index, name="index"),
    path("report", views.report, name="report"),
    path("generate_pdf", views.generate_pdf, name="generate_pdf"),
]

djangoapps/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("authenticator.urls")),
]

createbio/models.py
from django.db import models
from django.core.validators import MaxValueValidator

# Create your models here.
class biodata(models.Model):
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    contact = models.PositiveIntegerField(validators=[MaxValueValidator(9999999999)])
    email = models.EmailField(max_length=60)
    address = models.CharField(max_length=100)
    city = models.CharField(max_length=25)
    state = models.CharField(max_length=25)
    pincode = models.IntegerField(validators=[MaxValueValidator(999999)])
    gender = models.CharField(max_length=6)
    education = models.CharField(max_length=25)

createbio/forms.py
from django import forms

class BioForm(forms.Form):
    first_name = forms.CharField(max_length=25,
                    widget=forms.TextInput(
                    attrs={
                        'required':'required',
                        'placeholder':'Your first name',
                        'class':'form-control',
                        }
                    )
                )

    last_name = forms.CharField(max_length=25,
                    widget=forms.TextInput(
                    attrs={
                        'required':'required',
                        'placeholder':'Your last name',
                        'class':'form-control',
                        }
                    )
                )

    contact = forms.IntegerField(
                    widget=forms.NumberInput(
                    attrs={
                        'required':'required',
                        'placeholder':'Your Mobile Number',
                        'class':'form-control',
                        }
                    )
                )

    email = forms.EmailField(
                    widget=forms.EmailInput(
                    attrs={
                        'required':'required',
                        'placeholder':'Your EmailID',
                        'class':'form-control',
                        }
                    )
                )

    address = forms.CharField(max_length=100,
                    widget=forms.TextInput(
                    attrs={
                        'required':'required',
                        'placeholder':'Your Postal Address',
                        'class':'form-control',
                        }
                    )
                )

    city = forms.CharField(max_length=25,
                    widget=forms.TextInput(
                    attrs={
                        'required':'required',
                        'placeholder':'Your current city',
                        'class':'form-control',
                        }
                    )
                )

    state = forms.CharField(max_length=25,
                    widget=forms.TextInput(
                    attrs={
                        'required':'required',
                        'placeholder':'Your current state',
                        'class':'form-control',
                        }
                    )
                )

    pincode = forms.IntegerField(
                    widget=forms.NumberInput(
                    attrs={
                        'required':'required',
                        'placeholder':'pincode',
                        'class':'form-control',
                        }
                    )
                )

    gender = forms.CharField(max_length=25,
                    widget=forms.TextInput(
                    attrs={
                        'required':'required',
                        'placeholder':'gender',
                        'class':'form-control',
                        }
                    )
                )

    education = forms.CharField(max_length=25,
                    widget=forms.TextInput(
                    attrs={
                        'required':'required',
                        'placeholder':'Your highest degree',
                        'class':'form-control',
                        }
                    )
                )

createbio/views.py
import io
from django.shortcuts import render
from .forms import BioForm
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from .models import biodata
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4


# Create your views here.
def index(request):
    if request.method == "POST":
        form = BioForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            bio = biodata(first_name=first_name)
            bio.last_name = form.cleaned_data.get('last_name')
            bio.contact = form.cleaned_data.get('contact')
            bio.email = form.cleaned_data.get('email')
            bio.address = form.cleaned_data.get('address')
            bio.city = form.cleaned_data.get('city')
            bio.state = form.cleaned_data.get('state')
            bio.pincode = form.cleaned_data.get('pincode')
            bio.gender = form.cleaned_data.get('gender')
            bio.education = form.cleaned_data.get('education')
            bio.save()
            return render(request, "createbio/report.html", {
                'messages':'Registered successfully. Please generate report.',
            })
        else:
            form.errors()
            return HttpResponseRedirect(reverse("createbio:index"))
    else:
        form = BioForm()
        return render(request, "createbio/input.html", {
            'form':form
        })

def generate_pdf(request):
    response = HttpResponse(content_type='application/pdf')

    # Create a file-like buffer to receive PDF data.
    buffer = io.BytesIO()
    # Create the PDF object, using the buffer as its "file."
    p = canvas.Canvas(buffer, pagesize=A4)

    bio = biodata.objects.get(id=1)

    p.setFont("Helvetica", 16)
    p.drawString(267, 820, "Biodata")
    p.line(0,818,595,818)
    p.setTitle('Your Biodata')

    #fill with database data.
    p.setFont("Times-Bold", 12)
    p.drawString(25,800, "Name: ")
    p.drawString(25,780, "Mobile: ")
    p.drawString(25,760, "Email: ")
    p.drawString(25,740, "Gender: ")
    p.drawString(25,720, "Address: ")
    p.drawString(25,700, "City: ")
    p.drawString(25,680, "State: ")
    p.drawString(25,660, "Pincode: ")
    p.drawString(25,640, "Education: ")
    p.setFont("Helvetica", 12)
    p.drawString(60,800, bio.first_name + " " + bio.last_name)
    p.drawString(66,780, str(bio.contact))
    p.drawString(62,760, bio.email)
    p.drawString(72,740, bio.gender)
    p.drawString(72,720, bio.address)
    p.drawString(62,700, bio.city)
    p.drawString(62,680, bio.state)
    p.drawString(70,660, str(bio.pincode))
    p.drawString(82,640, bio.education)
    p.drawString(286,10, str(p.getPageNumber()))

    # Close the PDF object cleanly, and we're done.
    p.showPage()
    p.save()

    pdf = buffer.getvalue()
    buffer.close()
    response.write(pdf)

    return response

def report(request):
    return render(request, "createbio/report.html")

createbio/templates/createbio/input.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Create Your Bio</title>

    <!-- Link to CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'createbio/style.css' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    <!-- Favicon link -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicon_io/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon_io/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon_io/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'images/favicon_io/site.webmanifest' %}">
  </head>
  <body>
    <nav class="navbar">
      <div class="container">
        <ul class="nav navbar-nav navbar-left">
          <li class="active"><a href="{% url 'authenticator:index' %}"><img src="{% static 'images/logo.png' %}" alt="Logo" height="80px" width="180px"></a></li>
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body %}
        <h1>Welcome to the Biodata Creator App.</h1>
        <h2>Enter your details in the form below.</h2>
        
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-danger" style="text-align:center">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endfor %}
        {% endif %}

        <div class="biodata-form">
          <form action="{% url 'createbio:index' %}" method="post">
          {% csrf_token %}
              <div class="input-group mb-2 mr-sm-2">
                <div class="input-group-prepend">
                  <div class="input-group-text"><i class="fas fa-user"></i></div>
                </div>
                {{ form.first_name }}
              </div>
              <div class="input-group mb-2 mr-sm-2">
                <div class="input-group-prepend">
                  <div class="input-group-text"><i class="fas fa-user"></i></div>
                </div>
                {{ form.last_name }}
              </div>
              <div class="input-group mb-2 mr-sm-2">
                <div class="input-group-prepend">
                  <div class="input-group-text"><i class="fas fa-phone"></i></div>
                </div>
                {{ form.contact }}
              </div>
              <div class="input-group mb-2 mr-sm-2">
                <div class="input-group-prepend">
                  <div class="input-group-text"><i class="far fa-paper-plane"></i></div>
                </div>
                {{ form.email }}
              </div>
              <div class="input-group mb-2 mr-sm-2">
                <div class="input-group-prepend">
                  <div class="input-group-text"><i class="fas fa-address-card"></i></div>
                </div>
                {{ form.address }}
              </div>
              <div class="input-group mb-2 mr-sm-2">
                <div class="input-group-prepend">
                  <div class="input-group-text"><i class="fas fa-city"></i></div>
                </div>
                {{ form.city }}
              </div>
              <div class="input-group mb-2 mr-sm-2">
                <div class="input-group-prepend">
                  <div class="input-group-text"><i class="fas fa-address-card"></i></div>
                </div>
                {{ form.state }}
              </div>
              <div class="input-group mb-2 mr-sm-2">
                <div class="input-group-prepend">
                  <div class="input-group-text"><i class="fas fa-address-card"></i></div>
                </div>
                {{ form.pincode }}
              </div>
              <div class="input-group mb-2 mr-sm-2">
                <div class="input-group-prepend">
                  <div class="input-group-text"><i class="fas fa-user"></i></div>
                </div>
                {{ form.gender }}
              </div>
              <div class="input-group mb-2 mr-sm-2">
                <div class="input-group-prepend">
                  <div class="input-group-text"><i class="fas fa-university"></i></div>
                </div>
                {{ form.education }}
              </div>
              <br>
              <div class="form-group">
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                  <button type="submit" class="btn btn-primary btn-lg">Submit</button>
                  <button type="reset" class="btn btn-primary btn-lg" style="margin-left:70px;" value="Reset">Reset</button>
              </div>
          </form>
        </div>
      {% endblock %}
    </div>
  </body>
</html>

createbio/templates/createbio/report.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Create Your Bio</title>

    <!-- Link to CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'createbio/style.css' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    <!-- Favicon link -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicon_io/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon_io/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon_io/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'images/favicon_io/site.webmanifest' %}">
  </head>
  <body>
    <nav class="navbar">
      <div class="container">
        <ul class="nav navbar-nav navbar-left">
          <li class="active"><a href="{% url 'authenticator:index' %}"><img src="{% static 'images/logo.png' %}" alt="Logo" height="80px" width="180px"></a></li>
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body %}
      {% if messages %}
          <div class="alert alert-success" style="text-align:center">
            {{ message }}
          </div>
      {% endif %}

      <a href="{% url 'createbio:generate_pdf' %}" target="_blank" class="btn btn-sm btn-success">Generate Pdf</a>
      {% endblock %}
    </div>
  </body>
</html>