authenticator/urls.py
from django.urls import path

from . import views

app_name = "authenticator"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("register", views.register_view, name="register"),
    path("dashboard", views.dashboard_view, name="dashboard"),
    path("logout", views.logout_view, name="logout"),
]

createbio/urls.py
from django.urls import path

from . import views

app_name = "createbio"
urlpatterns = [
    path("", views.index, name="index"),
    path("report", views.report, name="report"),
    path("generate_pdf", views.generate_pdf, name="generate_pdf"),
]

djangoapps/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("authenticator.urls")),
]

authenticator/models.py
from django.db import models

# Create your models here.

authenticator/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    username = forms.IntegerField(
                widget=forms.NumberInput(
                attrs={
                    'required':'required',
                    'placeholder': 'Username',
                    'class': 'form-control'
                      }
                    )
                )
    first_name = forms.CharField(max_length=50,
                  widget=forms.TextInput(
                  attrs={
                        'required': 'required',
                        'placeholder': 'First name',
                        'class': 'form-control',
                        }
                    )
                )
    last_name = forms.CharField(max_length=50,
                  widget=forms.TextInput(
                  attrs={
                        'required': 'required',
                        'placeholder': 'Last name',
                        'class': 'form-control',
                        }
                    )
                )
    password1 = forms.CharField(
                 widget=forms.PasswordInput(
                 attrs={
                        'placeholder':'Password',
                        'required': 'required',
                        'class': 'form-control',
                        }
                    )
                )
    password2 = forms.CharField(
                 widget=forms.PasswordInput(
                 attrs={
                        'placeholder':'Confirm Password',
                        'required': 'required',
                        'class': 'form-control',
                        }
                    )
                )
    email = forms.EmailField(
             widget=forms.EmailInput(
             attrs={
                    'required': 'required',
                    'placeholder': 'Enter Email-id',
                    'class': 'form-control',
                    }
                )
            )

class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'password1', 'password2', 'email']

authenticator/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from .forms import RegisterForm
from django.urls import reverse
from django.contrib import messages

# Create your views here.
def index(request):
    return render(request, "authenticator/index.html")

def login_view(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("authenticator:dashboard"))
        else:
            return render(request, "authenticator/login.html", {
                'message': 'Invalid Credentials.'
            })
    else:
        return render(request, "authenticator/login.html")

def register_view(request):
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = RegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = form.save()
            user.first_name = form.cleaned_data.get('first_name')
            user.last_name = form.cleaned_data.get('last_name')
            user.email = form.cleaned_data.get('email')
            user.save()
            messages.success(request, 'Registered successfully. Please go to login page.')
            return HttpResponseRedirect(reverse("authenticator:register"))
        else:
            print(form.errors)
    else:
        form = RegisterForm()
    return render(request, "authenticator/register.html", {
        'form':form
    })

def dashboard_view(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("authenticator:login"))
    return render(request, "authenticator/dashboard.html")

def logout_view(request):
    #logout the user.
    logout(request)
    return render(request, "authenticator/logout.html")

authenticator/templates/authenticator/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Django Apps</title>

    <!-- Link to CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'authenticator/style.css' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    <!-- Favicon link -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicon_io/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon_io/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon_io/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'images/favicon_io/site.webmanifest' %}">
  </head>
  <body>
    <div class="container">
      {% block body %}
      {% endblock %}
    </div>
  </body>
</html>

authenticator/templates/authenticator/dashboard.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Django Apps</title>

    <!-- Link to CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'authenticator/style.css' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    <!-- Favicon link -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicon_io/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon_io/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon_io/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'images/favicon_io/site.webmanifest' %}">

  </head>
  <body>
    <div class="dashboard-header">
      <div class="dashboard-nav">
        <a href="#" data-toggle="collapse" aria-expanded="false" aria-controls="collapse"><span style="color:grey;float:left;padding:12px 16px;"><i class="fas fa-bars fa-lg"></i></span></a>
        <div class="collapse" id="collapse">
          <a href="#">Link1</a>
        </div>
      </div>
      <span style="text-align:right;color:grey">Last Login: {{ request.user.last_login }}</span>
      <div class="dropdown">
        <button class="dropbtn" style="padding-right:28px;padding-left:28px"><i class="fas fa-user"></i>&nbsp;{{ request.user.username }}</button>
        <div class="dropdown-content">
          <a href="{% url 'authenticator:dashboard' %}" style="font-size:16px; text-decoration:none"><i class="fas fa-tachometer-alt"></i>&nbsp;Dashboard</a>
          <a href="{% url 'authenticator:logout' %}" style="font-size:16px; text-decoration:none"><i class="fas fa-sign-out-alt"></i>&nbsp;Logout</a>
        </div>
      </div>
    </div>

    {% block body %}
    {% endblock %}
  </body>
</html>

authenticator/templates/authenticator/index.html
{% extends "authenticator/base.html" %}

{% block body %}
    <h1>Welcome to my home page.</h1>

{% endblock %}

authenticator/templates/authenticator/login.html
{% extends "authenticator/base.html" %}

{% block body %}

{% if message %}
<div class="alert alert-danger alert-dismissible" role="alert" style="text-align:center">
  {{ message }}
</div>
{% endif %}

  <div class="login-form">
    <form action="{% url 'authenticator:login' %}" method="post">
    {% csrf_token %}
        <h2 class="text-center">Login Form</h2>
        <div class="input-group mb-2 mr-sm-2">
          <div class="input-group-prepend">
            <div class="input-group-text"><i class="fas fa-user"></i></div>
          </div>
        	<input type="text" class="form-control" name="username" placeholder="Username" required="required">
        </div>
		    <div class="input-group mb-2 mr-sm-2">
          <div class="input-group-prepend">
            <div class="input-group-text"><i class="fas fa-lock"></i></div>
          </div>
          <input type="password" class="form-control" name="password" placeholder="Password" required="required">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-lg btn-block">Sign in</button>
        </div>
    </form>
  </div>
{% endblock %}

authenticator/templates/authenticator/logout.html
{% extends "authenticator/base.html" %}

{% block body %}

  <h1>You have successfully Logged Out.</h1>


  <h2 style="text-align:center">Thanks for spending some quality time with the site today.</h2>

{% endblock %}

authenticator/templates/authenticator/register.html
{% extends "authenticator/base.html" %}
{% load static %}

{% block body %}

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger" style="text-align:center">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
{% endif %}

{% if messages %}
    {% for message in messages %}
    <div class="alert alert-success" style="text-align:center">
      <strong{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</strong>
    </div>
    {% endfor %}
{% endif %}

<div class="register-form">
  <form action="{% url 'authenticator:register' %}" method="post">
  {% csrf_token %}
      <h2 class="text-center">Register Here</h2>
      <div class="input-group mb-2 mr-sm-2">
        <div class="input-group-prepend">
          <div class="input-group-text"><i class="fas fa-user"></i></div>
        </div>
        {{ form.first_name }}
      </div>
      <div class="input-group mb-2 mr-sm-2">
        <div class="input-group-prepend">
          <div class="input-group-text"><i class="fas fa-user"></i></div>
        </div>
        {{ form.last_name }}
      </div>
      <div class="input-group mb-2 mr-sm-2">
        <div class="input-group-prepend">
          <div class="input-group-text"><i class="fas fa-user"></i></div>
        </div>
        {{ form.username }}
      </div>
      <div class="input-group mb-2 mr-sm-2">
        <div class="input-group-prepend">
          <div class="input-group-text"><i class="far fa-paper-plane"></i></div>
        </div>
        {{ form.email }}
      </div>
      <!--div class="input-group mb-2 mr-sm-2">
        <div class="input-group-prepend">
          <div class="input-group-text"><i class="fas fa-phone"></i></div>
        </div>
        <input type="number" class="form-control" name="mobnum" placeholder="Mobile Number" required="required">
      </div-->
      <div class="input-group mb-2 mr-sm-2">
        <div class="input-group-prepend">
          <div class="input-group-text"><i class="fas fa-lock"></i></div>
        </div>
        {{ form.password1 }}
      </div>
      <div class="input-group mb-2 mr-sm-2">
        <div class="input-group-prepend">
          <div class="input-group-text"><i class="fas fa-lock"></i></div>
        </div>
        {{ form.password2 }}
      </div>
      <div class="form-group">
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          <button type="submit" class="btn btn-primary btn-lg">Sign Up</button>
          <button type="reset" class="btn btn-primary btn-lg" style="margin-left:70px;">Reset</button>
      </div>
  </form>
</div>

{% endblock %}