createbio/urls.py
from django.urls import path

from . import views

app_name = "createbio"
urlpatterns = [
    path("", views.index, name="index"),
    path("report", views.report, name="report"),
    path("generate_pdf", views.generate_pdf, name="generate_pdf"),
]

djangoapps/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("authenticator.urls")),
]

recruitment/urls.py
from django.urls import path

from . import views

app_name = "recruitment"
urlpatterns = [
    path("", views.index, name="index"),
    path("apply", views.apply, name="apply"),
]

recruitment/models.py
from django.db import models
from django.core.validators import MaxValueValidator

# Create your models here.
class PersonalDetails(models.Model):
    applicant_id = models.IntegerField()
    full_name = models.CharField(max_length=30)
    parent_name = models.CharField(max_length=30)
    dob = models.DateField()
    gender = models.CharField(max_length=12)
    category = models.CharField(max_length=15)
    mob_no = models.PositiveIntegerField(validators=[MaxValueValidator(9999999999)])
    email = models.EmailField(max_length=60)
    nationality = models.CharField(max_length=20)

recruitment/forms.py
from django import forms

gender_choices = (
        ('', 'Select Gender'),
        ('male', 'Male'),
        ('female', 'Female'),
        ('other', 'Other'),
)

class ApplyForm(forms.Form):
    full_name = forms.CharField(max_length=30,
                    widget=forms.TextInput(
                    attrs={
                        'required':'required',
                        'placeholder':'Your Full Name',
                        'class':'form-control',
                        }
                    )
                )

    parent_name = forms.CharField(max_length=30,
                    widget=forms.TextInput(
                    attrs={
                        'required':'required',
                        'placeholder':'Your Father/Husband name',
                        'class':'form-control',
                        }
                    )
                )

    dob = forms.DateField(
                    widget=forms.DateInput(
                    attrs={
                        'required':'required',
                        'placeholder':'Your BirthDate',
                        'class':'form-control',
                        'type':'date',
                        }
                    )
                )

    #gender = forms.CharField(max_length=12,
                    #widget=forms.TextInput(
                    #attrs={
                        #'required':'required',
                        #'placeholder':'gender',
                        #'class':'form-control',
                        #}
                    #)
                #)
    gender = forms.CharField(widget=forms.Select(choices=gender_choices, attrs={'class':'form-control', 'required':'required'})
            )

    category = forms.CharField(max_length=15,
                    widget=forms.TextInput(
                    attrs={
                        'required':'required',
                        'placeholder':'category',
                        'class':'form-control',
                        }
                    )
                )

    mob_no = forms.IntegerField(
                    widget=forms.NumberInput(
                    attrs={
                        'required':'required',
                        'placeholder':'Your Mobile Number',
                        'class':'form-control',
                        }
                    )
                )

    email = forms.EmailField(
                    widget=forms.EmailInput(
                    attrs={
                        'required':'required',
                        'placeholder':'Your EmailID',
                        'class':'form-control',
                        }
                    )
                )

    nationality = forms.CharField(max_length=20,
                    widget=forms.TextInput(
                    attrs={
                        'required':'required',
                        'placeholder':'Your Nationality',
                        'class':'form-control',
                        }
                    )
                )

recruitment/views.py
from django.shortcuts import render
from .forms import ApplyForm
from .models import PersonalDetails
from django.db.models import Max
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages

# Create your views here.
def index(request):
    return render(request, "recruitment/index.html")

def apply(request):
    if request.method == "POST":
        form = ApplyForm(request.POST)
        if form.is_valid():
            max_id = PersonalDetails.objects.all().aggregate(Max('id'))
            if max_id['id__max'] == None:
                max_id['id__max'] = 1
                applicant_id = 2021220000 + max_id['id__max']
            else:
                max_id = PersonalDetails.objects.all().aggregate(Max('applicant_id'))
                applicant_id = applicant_id + max_id['applicant_id__max']
            print(applicant_id)
            applicant = PersonalDetails(applicant_id=applicant_id)
            applicant.full_name = form.cleaned_data.get('full_name')
            applicant.parent_name = form.cleaned_data.get('parent_name')
            applicant.dob = form.cleaned_data.get('dob')
            applicant.gender = form.cleaned_data.get('gender')
            applicant.category = form.cleaned_data.get('category')
            applicant.mob_no = form.cleaned_data.get('mob_no')
            applicant.email = form.cleaned_data.get('email')
            applicant.nationality = form.cleaned_data.get('nationality')
            applicant.save()
            messages.success(request, 'Registered successfully. Please go to login page.')
            return HttpResponseRedirect(reverse("recruitment:apply"))
        else:
            print(form.errors)
    else:
        form = ApplyForm()
        return render(request, "recruitment/apply.html", {
            'form':form
        })

recruitment/templates/recruitment/apply.html
{% extends "recruitment/base.html" %}

{% block body %}
  <form action="#" method="post">
    {% csrf_token %}
    <div class="personal_info">
      <h5><b>Personal Details</b></h5>
      <div class="form-row">
        <div class="col-5">
          <div class="input-group mb-2">
            <div class="input-group-prepend">
              <div class="input-group-text"><i class="fas fa-user"></i></div>
            </div>
            {{ form.full_name }}
          </div>
          <small style="margin-left:40px;margin-top:-8px;margin-bottom:10px"class="form-text text-muted">(In <b>Block Letters</b> as per Xth/Matriculation Certificate)</small>
        </div>
        <div class="col-5">
          <div class="input-group mb-2" style="margin-left:100px;">
            <select>
              <option>Father</option>
              <option>Husband</option>
            </select>
            <div class="input-group-prepend">
              <div class="input-group-text"><i class="fas fa-user"></i></div>
            </div>
            {{ form.parent_name }}
          </div>
        </div>
      </div>
      <div class="form-row">
        <div class="col-5">
          <div class="input-group mb-2">
            <div class="input-group-prepend">
              <div class="input-group-text"><i class="fas fa-phone"></i></div>
            </div>
            {{ form.mob_no }}
          </div>
        </div>
        <div class="col-5">
          <div class="input-group mb-2" style="margin-left:100px;">
            <div class="input-group-prepend">
              <div class="input-group-text"><i class="far fa-paper-plane"></i></div>
            </div>
            {{ form.email }}
          </div>
        </div>
      </div>
      <div class="form-row">
        <div class="col-5">
          <div class="input-group mb-2">
            <div class="input-group-prepend">
              <div class="input-group-text"><i class="fas fa-address-card"></i></div>
            </div>
            {{ form.category }}
          </div>
        </div>
        <div class="col-5">
          <div class="input-group mb-2" style="margin-left:100px;">
            <div class="input-group-prepend">
              <div class="input-group-text"><i class="fas fa-city"></i></div>
            </div>
            {{ form.nationality }}
          </div>
        </div>
      </div>
      <div class="form-row">
        <div class="col-5">
          <div class="input-group mb-2">
            <div class="input-group-prepend">
              <div class="input-group-text"><i class="fas fa-user"></i></div>
            </div>
            {{ form.gender }}
          </div>
        </div>
        <div class="col-5">
          <div class="input-group mb-2" style="margin-left:100px;">
            <div class="input-group-prepend">
              <div class="input-group-text">BirthDate</div>
            </div>
            {{ form.dob }}
          </div>
        </div>
      </div>
    </div>
    <br>
    <div class="form-group">
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <button type="submit" class="btn btn-primary btn-lg">Submit</button>
        <button type="reset" class="btn btn-primary btn-lg" style="margin-left:70px;" value="Reset">Reset</button>
    </div>
  </form>

{% endblock %}

recruitment/templates/recruitment/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Recruitment Application</title>

    <!-- Link to CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'recruitment/style.css' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    <!-- Favicon link -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicon_io/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon_io/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon_io/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'images/favicon_io/site.webmanifest' %}">
  </head>
  <body>
    <div class="container">
      <div class="row justify-content-center" style="margin-top:5px;">
        <div class="col-1">
          <a href="{% url 'recruitment:index' %}"><img src="{% static 'images/Logo.jpg' %}" alt="Logo" width="40px" height="60px" /></a>
        </div>
        <div class="col-6">
          <h3>DAMODAR VALLEY CORPORATION</h3>
          <h4>दामोदर घाटी निगम</h4>
        </div>
      </div>
    </div>
    <div class="container">
      {% block body %}
      {% endblock %}
    </div>
  </body>
</html>

recruitment/templates/recruitment/index.html
{% extends "recruitment/base.html" %}

{% block body %}
  <div id="apply" class="d-flex justify-content-center">
    <a class="btn btn-primary" href="{% url 'recruitment:apply' %}" role="button">Apply Now</a>
  </div>
{% endblock %}